/* 부서 */
CREATE TABLE DEPT_EXERD (
	DEPTNO NUMBER(2) NOT NULL, /* 부서번호 */
	DNAME VARCHAR2(20) NOT NULL, /* 부서명 */
	LOC VARCHAR2(20) NOT NULL /* 위치 */
);

COMMENT ON TABLE DEPT_EXERD IS '부서';

COMMENT ON COLUMN DEPT_EXERD.DEPTNO IS '부서번호';

COMMENT ON COLUMN DEPT_EXERD.DNAME IS '부서명';

COMMENT ON COLUMN DEPT_EXERD.LOC IS '위치';

CREATE UNIQUE INDEX PK_DEPT_EXERD
	ON DEPT_EXERD (
		DEPTNO ASC
	);

ALTER TABLE DEPT_EXERD
	ADD
		CONSTRAINT PK_DEPT_EXERD
		PRIMARY KEY (
			DEPTNO
		);

/* 사원정보 */
CREATE TABLE EMP_EXERD (
	EMPNO NUMBER(4) NOT NULL, /* 사원번호 */
	ENAME VARCHAR2(10) NOT NULL, /* 사원명 */
	JOB VARCHAR2(10) NOT NULL, /* 직업 */
	MGR NUMBER(4) NOT NULL, /* 매니저 */
	HIREDATE DATE NOT NULL, /* 입사일 */
	SAL NUMBER(7,2) NOT NULL, /* 급여 */
	COMM NUMBER(7,2) NOT NULL, /* 성과급 */
	DEPTNO NUMBER(2) /* 부서번호 */
);

COMMENT ON TABLE EMP_EXERD IS '사원정보';

COMMENT ON COLUMN EMP_EXERD.EMPNO IS '사원번호';

COMMENT ON COLUMN EMP_EXERD.ENAME IS '사원명';

COMMENT ON COLUMN EMP_EXERD.JOB IS '직업';

COMMENT ON COLUMN EMP_EXERD.MGR IS '매니저';

COMMENT ON COLUMN EMP_EXERD.HIREDATE IS '입사일';

COMMENT ON COLUMN EMP_EXERD.SAL IS '급여';

COMMENT ON COLUMN EMP_EXERD.COMM IS '성과급';

COMMENT ON COLUMN EMP_EXERD.DEPTNO IS '부서번호';

CREATE UNIQUE INDEX PK_EMP_EXERD
	ON EMP_EXERD (
		EMPNO ASC
	);

ALTER TABLE EMP_EXERD
	ADD
		CONSTRAINT PK_EMP_EXERD
		PRIMARY KEY (
			EMPNO
		);

ALTER TABLE EMP_EXERD
	ADD
		CONSTRAINT FK_DEPT_EXERD_TO_EMP_EXERD
		FOREIGN KEY (
			DEPTNO
		)
		REFERENCES DEPT_EXERD (
			DEPTNO
		);